version: '3'
services:
  azgoapi:
    image: xtforgame/azgoapi:0.1
    build:
      context: https://github.com/xtforgame/azgoapi.git#:dist/alpine3.9
      dockerfile: ./Dockerfile

    container_name: azgoapi

    command: ["/usr/bin/azgoapi", "--config=config.yml"]

    volumes:
      - "./config.yml:/usr/azgoapi/config.yml"
      - "./runtime:/usr/azgoapi/runtime"
